import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="flex flex-col min-h-screen">
          <div className="md:px-20 ">
            <Header />
          </div>
          <div className="flex-grow">
            {children}
          </div>
          <Toaster />
          <div>
            <Footer />
          </div>

        </div>
      </body>
    </html>
  );
}
